select top(20) * from customer;

-- 1. what is total reveneue generated by male and female customers?
select gender, sum(purchase_amount) as total_purchase_amount 
from customer 
group by gender;

-- 2. which customer used a discount but still spent more than avg purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and 
purchase_amount > (select avg(purchase_amount) from customer);

-- 3. what are the top 5 products with the highest average review rating?
select top(5) item_purchased, avg(review_rating) as avg_rating
from customer
group by item_purchased 
order by avg(review_rating) desc;

--4. comapre the avg purchase amount between standard and express shippng
SELECT shipping_type,
       AVG(purchase_amount) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type;

--5. do subscribed customers spend more? compare avg spend and total revenue between subscribers and non_subsribers.

select subscription_status, count(customer_id) as total_customer, avg(purchase_amount) as avg_spend , sum(purchase_amount)as total_revenue from customer
group by subscription_status;

--6. which products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,
round(sum(case when discount_applied = 'Yes' then 1 else 0 end) * 100 /count(*),2 ) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
 
--7. segment customers into new, returning, and loyal based on their total 
--number of previous purchases and show the count of each segment.

--1 to 50
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer)

select customer_segment, count(*) as 'Number of customers'
from customer_type
group by customer_segment;

--8. what are the top 3 most purchased products within each category?
with item_count as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category item_purchased, total_orders
from item_count
where item_rank <=3;

--9. are customers who are repeat buyers (more than 5) also likely to subscribe?
select top 20 * from customer;

select 
subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

--10. what is the revenue contribution in each group?
select age_group,
sum(purchase_amount) as total_revenue 
from customer
group by age_group;